---
title: "Plots"
author: "Aleksandra Dacko"
date: "11/24/2022"
output: html_document
---

Here I have created the plot function for dwell time duration
```{r, warning=FALSE}
library(ggplot2)
library(RColorBrewer)
set.seed(123)
plot_lognorm<-function(m, means){
  meanlog<-sort(means)
  col<-brewer.pal(m, name='Dark2')
  datay<-dlnorm(seq(0,12,0.1), meanlog=log(meanlog[1]),sdlog = 1)
  med<-median(datay)
  data<-data.frame(x=seq(0,12,0.1),y=datay)
  plot<-ggplot(data=data,aes(x=x,y=y))+geom_line(color=col[1],size=1)+theme_bw()+ylab("density")+xlab("duration distribution")+ggtitle("EDHMM state dependent lognormal dwell time distribution ")+xlim(c(0,12))#+geom_hline(yintercept = med,color=col[1])
  for(s in 2:m){
    datay<-dlnorm(seq(0,12,0.1),meanlog =log(meanlog[s]),sdlog = 1)
    med<-median(datay)
    data<-data.frame(x=seq(0,12,0.1),y=datay)
    plot<-plot+geom_line(data=data,aes(x=x,y=y),color=col[s],size=1)#+geom_hline(yintercept = med,color=col[s])
  }
  return(plot)
}

set.seed(123)
data<-density(rlnorm(20000, log(15), sqrt(log(25))),from=-1,to=150)
set.seed(123)
data1<-density(rlnorm(20000, log(15), log(sqrt(25))),from=-1,to=150)#it is than correct
set.seed(123)
data2<-density(rlnorm(20000, log(15), log(5)),from=-1,to=150)

plot_lognorm(m=3,means=c(0.9,0.7,0.5))
plot_lognorm(m=3,means=c(6.5,6,5.5))

```


```{r}
#overlapping distribution plots
library(ggplot2)
library(RColorBrewer)
thm<-theme(
  axis.text.x = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  axis.title.x =element_blank(),
  axis.title.y = element_blank(),
  axis.line = element_line(colour = "black",size = 2),
  panel.background =element_blank())
col<-brewer.pal(3, name='Dark2')
data<-density(rlnorm(30000, log(5), log(10)),from=-1,to=100)
data<-data.frame(x=data$x,y=data$y)
data1<-density(rlnorm(30000, log(15), log(10)),from=-1,to=100)
data1<-data.frame(x=data1$x,y=data1$y)
data2<-density(rlnorm(30000, log(25), log(10)),from=-1,to=100)
data2<-data.frame(x=data2$x,y=data2$y)
p1<-ggplot(data=data,aes(x=data$x,y=data$y))+geom_line(color=col[1],size=3)+
  geom_line(data=data1,aes(x=x,y=y),color="grey",size=3)+
  geom_line(data=data2,aes(x=x,y=y),color="grey",size=3)+thm+xlim(c(0,70))
ggsave(file="logs_ex1.svg", plot=p1, width=10, height=8)
p2<-ggplot(data=data1,aes(x=data1$x,y=data1$y))+geom_line(color=col[2],size=3)+
  geom_line(data=data,aes(x=x,y=y),color="grey",size=3)+
  geom_line(data=data2,aes(x=x,y=y),color="grey",size=3)+thm+xlim(c(0,70))
ggsave(file="logs_ex2.svg", plot=p2, width=10, height=8)
p3<-ggplot(data=data2,aes(x=x,y=y))+geom_line(color=col[3],size=3)+
  geom_line(data=data1,aes(x=x,y=y),color="grey",size=3)+
  geom_line(data=data,aes(x=x,y=y),color="grey",size=3)+thm+xlim(c(0,70))
ggsave(file="logs_ex3.svg", plot=p3, width=10, height=8)
```
