#!/bin/bash

# see https://surfsara.nl/systems/lisa/software/stopos-example-1


module load 2021
module load R/4.1.0-foss-2021a
export MKL_NUM_THREADS=96   # to avoid that jobs compete for cores
export R_LIBS=$HOME/rpackages:$R_LIBS   # Refer to the folder where you 
                                        # have stored your R libraries


# IMPORTANT
# The first entry of the array is referred to as 0 in unix (but not in the R-script!)
# so here we have entries 0,1,2,3, not 1,2,3,4!!

# The name of the file containing your R-script
jobfile=convergence_runs.R



# Specify the folders where your R-script/data are
#  and where the results need to be written to
datadir=$HOME/convergence_run/mhmm
outdir=$HOME/convergence_run/mhmm/outputs


# Copy the job to a temporary folder in which the job is run
cp $datadir/$jobfile "$TMPDIR"
cd $TMPDIR || exit

# Run R: 
Rscript --slave --no-save $jobfile 


